### PR TITLE
Replace Reids.createClient argument from EventLoopGroup to EventLoop

### PR DESCRIPTION
**Pull request by vkill**
Hi

To make RedisClient just required EventLoop.

Please review it. thanks.

### CODE REVIEW

**Comment by helje5** [comment]
Please separate the PR into one for the tests, and another one for the API changes. I think the latter is actually superfluous. A NIO EventLoop is a EvenLoopGroup as well. So what is the point in limiting this?

**Comment by vkill** [comment]
> A NIO EventLoop is a EvenLoopGroup

eventLoop !== eventLoop.next()

**Comment by helje5** [comment]
At least in the NIO version I use it is exactly that, [EventLoop.swift](https://github.com/apple/swift-nio/blob/1.8.0/Sources/NIO/EventLoop.swift#L218):

```swift
    public func next() -> EventLoop {
        return self
    }
```

**Comment by vkill** [comment]
Oh, you are right. we should keep EventLoopGroup in library.

**Pull request closed without merging**
